Creación de pipeline y sast con sonar parte 2

diff --git a/.github/workflows/pipelineIC.yml b/.github/workflows/pipelineIC.yml
--- a/.github/workflows/pipelineIC.yml
+++ b/.github/workflows/pipelineIC.yml
@@ -46,3 +46,16 @@ jobs:
           -Dsonar.organization=devsecopsarielmarihuen
           -Dsonar.sources=.
           -Dsonar.exclusions=**/node_modules/**
+     - name: Check Quality Gate Status
+        run: |
+          echo "Checking Quality Gate status"
+          RESPONSE=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
+          "https://sonarcloud.io/api/qualitygates/project_status?projectKey=ArielAndresMarihuenMatus_Laboratorio-final")
+          echo "SonarCloud response: $RESPONSE"
+          SONAR_STATUS=$(echo "$RESPONSE" | jq -r .projectStatus.status)
+          if [ "$SONAR_STATUS" != "OK" ]; then
+            echo "Quality Gate failed: $SONAR_STATUS"
+            exit 1
+          else
+            echo "Quality Gate passed: $SONAR_STATUS"
+          fi
